if (DEFINED _FILTER_CMAKE)
    return()
endif()
set(_FILTER_CMAKE yes)

function(filter_assignSourceGroups)
    foreach(_source IN ITEMS ${ARGN})
        if (IS_ABSOLUTE "${_source}")
            file(RELATIVE_PATH _source_rel "${CMAKE_CURRENT_SOURCE_DIR}" "${_source}")
        else()
            set(_source_rel "${_source}")
        endif()
        get_filename_component(_source_path "${_source_rel}" PATH)
        string(REPLACE "${Config.SourceCodeRootPath}" "" _source_path_msvc "${_source}")
        string(FIND "${_source_path_msvc}" "/" _index REVERSE)
        string(SUBSTRING "${_source_path_msvc}" 0 ${_index} _source_path_msvc)
        string(REPLACE "/" "\\" _source_path_msvc "${_source_path_msvc}")
        source_group("${_source_path_msvc}" FILES "${_source}")
    endforeach()
endfunction()
